name: marwan_s_application10
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=3.3.3 <4.0.0'
dependencies: 
  flutter: 
    sdk: flutter

  cached_network_image: ^3.3.0
  image_picker: ^1.1.2
  dio: ^5.4.3+1
  uuid: ^4.4.0
  flutter_svg: ^2.0.9
  intl: ^0.18.0
  provider: ^6.1.2

dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: DM Sans
      fonts: 
        - asset: assets/fonts/DMSansMedium.ttf
          weight: 500
        - asset: assets/fonts/DMSansBold.ttf
          weight: 700
        - asset: assets/fonts/DMSansRegular.ttf
          weight: 400
